"""added on delete cascade and on update cascade constraints

Revision ID: 6209f9f8d606
Revises: 014a1dc5b5e8
Create Date: 2026-07-21 11:49:16.811277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6209f9f8d606'
down_revision: Union[str, Sequence[str], None] = '014a1dc5b5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_category_category_id_fkey'), 'product_category', type_='foreignkey')
    op.drop_constraint(op.f('product_category_product_id_fkey'), 'product_category', type_='foreignkey')
    op.create_foreign_key(None, 'product_category', 'category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_category', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('review_product_id_fkey'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('review_user_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_user_id_fkey'), 'review', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('review_product_id_fkey'), 'review', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.create_foreign_key(op.f('product_category_product_id_fkey'), 'product_category', 'product', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_category_category_id_fkey'), 'product_category', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
